### ISSUE TITLE
Running the workflow with PMC on lassen.

### ISSUE THREAD

**Issue by hariharan-devarajan** [pegasus-isi/1000genome-workflow#1]
I am running the workflow with pmc on lassen. I am getting the following error.

```
Traceback (most recent call last):
          File "/p/gpfs1/iopp/temp/1000-genome/scratch/run_dir/./individuals_merge", line 74, in <module>
            merging(c=sys.argv[1], tar_files=sys.argv[2:])
          File "/p/gpfs1/iopp/temp/1000-genome/scratch/run_dir/./individuals_merge", line 54, in merging
            writefile(merged_dir+'/'+file, content)
          File "/p/gpfs1/iopp/temp/1000-genome/scratch/run_dir/./individuals_merge", line 29, in writefile
            with open(file, 'w') as f:
        FileNotFoundError: [Errno 2] No such file or directory: 'merged//chr4.HG00096'
```

[1000-genome-run-dir.tar.gz](https://github.com/pegasus-isi/1000genome-workflow/files/7989005/1000-genome-run-dir.tar.gz)

**Comment by papajim** [comment]
Hi Hari,

I speculate that on the shared filesystem an individuals_merge job finished faster than the rest and deleted the merged folder.
Each inividuals_merge job now has a unique directory. Please pull the latest changes on master and try one more time.

**Comment by hariharan-devarajan** [comment]
Ok i pulled the code. Now it fails at
```
        Traceback (most recent call last):
          File "/p/gpfs1/iopp/temp/1000-genome/scratch/run_dir/./frequency", line 50, in <module>
            os.makedirs(plot_dir)
          File "/usr/WS2/iopp/software/spack/var/spack/environments/genome-pegasus/.spack-env/._view/2zx3zs6yvhqdgchk7s4yiukhdvwqw7xb/lib/python3.9/os.py", line 225, in makedirs
            mkdir(name, mode)
        FileExistsError: [Errno 17] File exists: './plots_no_sift/'
```

**Comment by papajim** [comment]
Did similar changes in frequency and mutation overlap jobs.
Can you pull the latest commit and try this one more time?

**Comment by hariharan-devarajan** [comment]
I added this to the code.
```
[genome-pegasus] [haridev@lassen709:1000genome-workflow]$ git diff bin/frequency.py
diff --git a/bin/frequency.py b/bin/frequency.py
index fc32871..3a30813 100755
--- a/bin/frequency.py
+++ b/bin/frequency.py
@@ -45,9 +45,9 @@ outdata_dir = './output_no_sift/'
 plot_dir = './plots_no_sift/'
 
 if not os.path.exists(outdata_dir):
-    os.makedirs(outdata_dir)
+    os.makedirs(outdata_dir, exist_ok = True)
 if not os.path.exists(plot_dir):
-    os.makedirs(plot_dir)
+    os.makedirs(plot_dir, exist_ok = True)
 
 OutputFormat = '.png'
```

it seems to complete now successfully. 
I will revert the change and try your fix.

**Comment by hariharan-devarajan** [comment]
I tried your fix. It worked. 

I will close the issue.
